great-h/great-h.github.io

_posts/2014-12-24-event-084.markdown, users.yml
#1437
これで良かったんだっけ、
１週間前の事も忘れている。。。
=> yasu7riの結果を記入 084 #1437

_posts/2014-12-31-event-085.markdown
=> #1454 もりしーの2014年を振り返ってみる

_posts/2014-12-31-event-085.markdown
=> 1451-tsudaa

_posts/2014-12-24-event-084.markdown
=> すごい広島82 - eielの成果

_posts/2014-12-31-event-085.markdown
doorkeeper に登録せずにエア参加してしまったものの、pull request を作成致しました。
よろしくお願いいたします。
=> すごい広島 85 の Nyoho のやったことを追記

_posts/2014-12-31-event-085.markdown
=> すごい広島85 - eielの成果

_posts/2014-12-31-event-085.markdown
=> kwgchの結果を記入 085

_posts/2015-01-07-event-086.markdown
=> すごい広島 86での進捗を追記しました

_posts/2014-12-31-event-085.markdown
=> yasu7riの結果を記入 085 #1446

_posts/2015-01-07-event-086.markdown
=> すごい広島86 eielの成果

_posts/2015-01-07-event-086.markdown
=> kwgchの結果を記入 086

_posts/2015-01-28-event-089.markdown
=> すごい広島89のぺージつくったよ。

_posts/2015-01-14-event-087.markdown
=> すごい広島87 eielの成果

_posts/2015-01-14-event-087.markdown
=> kwgchの結果を記入 087

_posts/2015-01-21-event-088.markdown
=> kwgchの結果を記入 088

_posts/2015-01-28-event-089.markdown
=> kwgchの結果を記入 089

_posts/2015-01-21-event-088.markdown
=> すごい広島88 - eielの成果

_posts/2015-02-11-event-091.markdown
=> すごい広島91の申し込みページ作成

_posts/2015-01-28-event-089.markdown
=> すごい広島 89 - eielの成果

_posts/2015-02-04-event-090.markdown
=> kwgchの結果を記入 090

_posts/2015-02-04-event-090.markdown
正確には取材をうけていたため成果がない。
close #1522
=> すごい広島90 - eielの成果

_posts/2015-02-11-event-091.markdown
=> すごい広島91 - eielの成果

_posts/2015-02-18-event-092.markdown
=> すごい広島92 - eiel

_posts/2015-02-18-event-092.markdown
=> kwgchの結果を記入 092

_posts/2015-02-25-event-093.markdown
=> すごい広島93 - eielの成果

_posts/2015-02-25-event-093.markdown
=> kwgchの結果を記入 093

_posts/2015-03-04-event-094.markdown
=> kwgchの結果を記入 094

_posts/2015-03-04-event-094.markdown
=> すごい広島 94 - eielの成果

_posts/2015-03-11-event-095.markdown
=> 1568 digital09

_posts/2015-03-11-event-095.markdown
=> すごい広島95 - eiel の成果

_posts/2015-03-11-event-095.markdown
遅くなりましたが #1566 のブログを書いたのでプルリクエストです。
=> #1566 nishimotz

_posts/2015-03-18-event-096.markdown
=> すごい広島96 - eielの YWT

_posts/2015-03-18-event-096.markdown
RSpecによるRailsテスト入門読了
パークマップ広島プロジェクトの週次レビュー実施
close #1574
=> 第９６回実績報告 #1574

_posts/2015-03-25-event-097.markdown
=> すごい広島97 - eiel成果

_posts/2015-04-01-event-098.markdown
=> すごい広島98 - eiel

_posts/2015-04-08-event-099.markdown
=> すごい広島99 - eielの成果

_posts/2015-04-15-event-100.markdown
=> すごい広島100 - eiel

_posts/2015-04-29-event-102.markdown
=> add member

_posts/2015-05-06-event-103.markdown
=> すごい広島103 - eiel

_posts/2015-05-13-event-104.markdown
=> すごい広島104 - eielの成果

_posts/2015-05-20-event-105.markdown
=> すごい広島105 - eielの成果

_posts/2015-05-27-event-106.markdown
=> すごい広島106 - eiel

_posts/2015-06-03-event-107.markdown
=> すごい広島107 eielの成果

_posts/2015-06-10-event-108.markdown
=> すごい広島109 - eielの成果

_posts/2015-06-24-event-110.markdown
=> すごい広島110のぺーじを作成

_posts/2015-06-17-event-109.markdown
=> すごい広島 109 - eiel

_posts/2015-07-01-event-111.markdown
=> やったことを追加した

_posts/2015-07-01-event-111.markdown, _posts/2015-07-08-event-112.markdown
=> すごい広島111 - eiel

_posts/2015-07-08-event-112.markdown
=> すごい広島112 - eiel

_posts/2015-07-15-event-113.markdown
=> すごい広島113 - eiel

_posts/2015-07-22-event-114.markdown
=> Issue 1669/tsuda ahr

_posts/2015-07-22-event-114.markdown
=> すごい広島114 - eiel

_posts/2015-07-29-event-115.markdown
=> すごい広島115 - eielの成果

_posts/2015-08-05-event-116.markdown
=> すごい広島116 - eielの成果

_posts/2015-08-12-event-117.markdown
=> すごい広島117 - eiel

_posts/2015-08-05-event-116.markdown, _posts/2015-08-12-event-117.markdown
=> Issue 1686/tsuda ahr

link.markdown
=> HMCTとMT Hiroshimaを追加

_posts/2015-08-19-event-118.markdown
=> すごい広島118 - eiel

_posts/2015-10-07-event-125.markdown
=> すごい広島125のページを作成

_posts/2015-09-30-event-124.markdown
=> すごい広島124 - eiel

_posts/2015-10-07-event-125.markdown
=> すごい広島125 - eiel

_posts/2015-10-28-event-128.markdown
=> すごい広島128 - eiel

_posts/2015-11-04-event-129.markdown
=> すごい広島 129 - eiel

_posts/2015-12-30-event-137.markdown
=> すごい広島 137の成果 - eiel

_posts/2016-02-24-event-145.markdown
https://github.com/great-h/great-h.github.io/issues/1762
レビューをお願い致します。
=> すごい広島 145 Nyoho のやったことを追加

_posts/2016-02-24-event-145.markdown
=> すごい広島 145 - eielhのやったこと

_posts/2016-03-02-event-146.markdown
追記致しました。なんとか時間をかけてフレームワークを完成させたいです。
close #1775
=> すごい広島 146 Nyoho のやったことを追記

_posts/2016-03-02-event-146.markdown
=> すごい広島146 - eiel

_posts/2016-03-09-event-147.markdown
48時間でSchemeを書こうの練習問題 2.5 を解きました
close #1780
=> すごい広島 147 - furu のやったこと

_posts/2016-03-16-event-148.markdown
=> 20160316の進捗を追記しました

.gitignore, _posts/2016-04-06-event-151.markdown
今日やることリストにrule.htmlを触ると書きましたが、
スタイルシートうまく触れそうになかったので、中止します。
scssかstylusのコンパイル環境作れたら、いつか触ります。
=> Issue 1793/akifo

_posts/2016-04-06-event-152.markdown, _posts/2016-04-20-event-153.markdown, app/app.rb, app/views/layouts/application.slim
dateのパースが失敗するのでどこで失敗するのかわかるように
=> dateがparseできなかったファイルを確認できるように

_posts/2016-07-06-event-164.markdown
=> すごい広島 164 - kwgchのやったこと

link.markdown
=> 広島フロントエンド勉強会(仮)を追加

_posts/2016-11-23-event-184.markdown
=> すごい広島 184 ・蒋

_posts/2016-11-30-event-185.markdown
蒋はやったこと
・Vapor Templateを勉強する
・Vapor Controllerを勉強する
=> すごい広島 185 #1848

.gitignore, app/views/index.slim
https://github.com/great-h/great-h.github.io/issues/1646 参照
=> 参加するボタンのリンク先をconpassに変更しました
